version: '2'
services:
  db:
    image: mongo:6.0.2
    restart: always
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db
  frontend:
    image: node:19
    user: "node"
    ports:
      - "3001:3001"
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: "yarn start"
    depends_on:
      - backend
